config/routes.rb
Rails.application.routes.draw do
  resources :employee_messages
  resources :mails
  resources :employee_tasks
  resources :tasks
  resources :projects
  resources :managers
  resources :employees
  resources :login, only: [:new, :create]

  root 'application#hello'
  post "/message_redirect", to: "common_pages#message_redirect", as: "message_redirect"
  get "/logout", to: "login#destroy", as: "logout"
  get "/show/:username", to: "common_pages#show", as: "common_show"
  get "/managers/:id/edit_employees", to: "managers#edit_employees", as: "edit_employees"
  post "/employees/got_fired", to: "employees#got_fired", as: "got_fired"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :employee_tasks, :dependent => :destroy
  has_many :tasks, through: :employee_tasks
  has_many :mails, :dependent => :destroy
  belongs_to :manager

  has_many :sent_employee_messages, :foreign_key => 'sender_id', class_name: "EmployeeMessage", :dependent => :destroy
  has_many :sent_employee_messages_to, through: :sent_employee_messages, source: :receiver

  has_many :received_employee_messages, :foreign_key => 'receiver_id', class_name: "EmployeeMessage", :dependent => :destroy
  has_many :received_employee_messages_from, through: :received_employee_messages, source: :sender

  has_secure_password

  validates :username, uniqueness: true


end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :find_employee
  skip_before_action :authorized?, only: [:new, :create, :destroy]
  def show
    if @employee.username == session[:user_username]
      @employeetasks = @employee.employee_tasks
      @employee_messages = @employee.received_employee_messages.sort_by {|messages| mail.id}.reverse
      @employee_manager_messages = @employee.mails.select {|mail| mail.sender != @employee.username}.sort_by {|mail| mail.id}.reverse
      @employee_sent_messages = @employee.sent_employee_messages.sort_by {|messages| mail.id}.reverse
      @employee_sent_manager_messages = @employee.mails.select {|mail| mail.sender == @employee.username}.sort_by {|mail| mail.id}.reverse
      @coworkers = @employee.manager.employees - [@employee]
      message_list_temp = @employee.manager.employees - [@employee]
      @message_list = message_list_temp
      @message_list << @employee.manager
      @quote = Faker::Games::LeagueOfLegends.quote
    else
      redirect_to common_show_path(:username => @employee.username)
    end
  end

  def new
    @employee = Employee.new
  end

  def create
    # byebug
    params[:employee][:username] = "emp" << params[:employee][:username]
    employee = Employee.create(employee_params(:name, :username, :password, :manager_id))
    redirect_to new_login_path
  end

  def edit

  end

  def update
    if @employee.username == session[:user_username]
      return redirect_to @user
    end
    password = params[:employee][:password]
    password2 = params[:employee][:confirm_password]
    if @utility.double_chack_passowrd(password, password2)
      @employee.update(employee_params(:name, :password))
      redirect_to @employee
    else
      flash[:messages] = "Password is not match"
      redirect_to @edit_account_path
    end
  end

  def employee_params(*argu)
    params.require(:employee).permit(*argu)
  end

  def got_fired
    employee = Employee.find_by(id: params[:employee_id])
    employee.destroy
    redirect_to edit_employees_path(Manager.find_by(username: session[:user_username]))
  end

  def destroy
    @employee.destroy
    session[:user_username] = nil
    redirect_to "/"
  end
end

def find_employee
  @employee = Employee.find_by(id: params[:id])
  @quote = Faker::Games::LeagueOfLegends.quote
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/edit.html.erb
<div class="jumbotron">
  <div class="container text-center">
    <h1>Account Setting</h1>
    <h2><%= @employee.name %></h2>
    <p><%= @quote %></p>
  </div>
</div>

<div class="emp_container container-fluid text-center">
  <div class="row content">
    <div class="col-sm-4 sidenav">
    </div>
    <div class="emp_form col-sm-4 text-left">
    <div class="form_cont">
      <h2>Edit Account</h2>
      <% if flash[:messages] %>
        <p><%= flash[:messages] %></p>
      <% end %>
      <%= form_for @employee do |f|%>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, :class => "form-control", placeholder: 'Name' %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, :class => "form-control", placeholder: 'Password' %>
        </div>
        <div class="form-group">
          <%= f.label "Confirm Password" %>
          <%= f.password_field :confirm_password, :class => "form-control", placeholder: 'Confirm Password' %>
        </div>
        <%= submit_tag "Update", :class => "btn btn-primary"%>
      <% end %>
      <button class="btn btn-danger" data-toggle="collapse" data-target="#demo">Delete Account</button>
      <div id="demo" class="collapse">
        <%= form_tag employee_path(@employee), method: :"delete" do %>
          <%= submit_tag "confirm", :class => "btn btn-danger" %>
        <% end %>
      </div>
      </div>
    </div>
    <div class="col-sm-4 sidenav">
    </div>
  </div>
</div>

app/views/employees/new.html.erb
<div class="emp_container container-fluid text-center">
  <div class="row content">
    <div class="col-sm-4 sidenav">
    </div>
    <div class="emp_form col-sm-4 text-left">
    <div class="form_cont">
      <h1>Welcome</h1>
      <h2>Employees Login</h2>
      <% if flash[:messages] %>
        <p><%= flash[:messages] %></p>
      <% end %>
      <%= form_for @employee do |f|%>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, :class => "form-control", placeholder: 'Name' %>
        </div>
        <div class="form-group">
          <%= f.label :username %>
          <%= f.text_field :username, :class => "form-control", placeholder: 'Username' %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, :class => "form-control", placeholder: 'Password' %>
        </div>
        <div class="form-group">
          <%= f.label :manager_id, "Invitation Code" %>
          <%= f.text_field :manager_id, :class => "form-control", placeholder: 'Invitation Code' %>
        </div>
        <%= submit_tag "Submit", :class => "btn btn-primary"%>
      <% end %>
      </div>
    </div>
    <div class="col-sm-4 sidenav">
    </div>
  </div>
</div>

app/views/employees/show.html.erb
<div class="jumbotron well">
  <div class="container">
    <h1 class="display-3"><%= @employee.name %></h1>
    <h3>Employee</h3>
    <p><%= @quote %></p>
  </div>
</div>


<div class="container-fluid ">
  <div class="row content ">
    <div class="col-sm-3 emp-inbox">
      <div class="well" style="margin-top: 20px;">
      <ul class="nav nav-pills nav-stacked">
        <li class="active inbox"><a data-toggle="collapse" href="#inbox">Inbox<span class="badge"><%= @employee_messages.count + @employee_manager_messages.count %></span></a></li>
        <div id="inbox" class="panel-collapse collapse">
          <ul>
            Manager Messages
            <% if @employee_manager_messages == [] %>
              <p>No Message</p>
            <% else %>
              <% @employee_manager_messages.each do |message| %>
                <li><a data-toggle="collapse" href=<%= "#mag_mesg" + "#{message.id}" %>><%= message.title %> form <%= @utility.sender_name(message) %></a></li>
                <div id=<%= "mag_mesg#{message.id}" %> class="panel-collapse collapse">
                  <%= message.content %>
                </div>
              <% end %>
            <% end %>
          </ul>
          <br>
          <ul>
            Employee Messages
            <% if @employee_messages == [] %>
              <p>No Message</p>
            <% else %>
              <% @employee_messages.each do |message| %>
                <li><a data-toggle="collapse" href=<%= "#emp_mesg" + "#{message.id}" %>><%= message.title %> form <%= message.sender.name %></a></li>
                <div id=<%= "emp_mesg#{message.id}" %> class="panel-collapse collapse">
                  <%= message.content %>
                </div>
              <% end %>
            <% end %>
          </ul>
          <br>
          <ul>
            Sent Messages
            <li><a data-toggle="collapse" href="#sent_manager">Message to Manager</a></li>
            <div id="sent_manager" class="panel-collapse collapse">
            <% if @employee_sent_manager_messages == [] %>
              <p>No Message</p>
            <% else %>
              <ul>
                <% @employee_sent_manager_messages.each do |message| %>
                  <li><a data-toggle="collapse" href=<%= "#sent_mesg" + "#{message.id}" %>><%= message.title %> to <%= @utility.receiver_name(message) %></a></li>
                  <div id=<%= "sent_mesg#{message.id}" %> class="panel-collapse collapse">
                    <%= message.content %>
                  </div>
                <% end %>
              </ul>
            <% end %>
            </div>
            <li><a data-toggle="collapse" href="#sent_employee">Message to Employee</a></li>
            <div id="sent_employee" class="panel-collapse collapse">
            <% if @employee_sent_messages == [] %>
              <p>No Message</p>
            <% else %>
              <ul>
                <% @employee_sent_messages.each do |message| %>
                  <li><a data-toggle="collapse" href=<%= "#empsent" + "#{message.id}" %>><%= message.title %> to <%= message.receiver.name %></a></li>
                  <div id=<%= "empsent#{message.id}" %> class="panel-collapse collapse">
                    <%= message.content %>
                  </div>
                <% end %>
              </ul>
            <% end %>
            </div>
          </ul>
          <br>
        </div>
        <li class="active"><a data-toggle="collapse" href="#message">Send Message</a></li>
        <div id="message" class="panel-collapse collapse">
          <%= form_tag "/message_redirect", method: :"post" do%>
            <%= label_tag "Send to" %>
            <%= collection_select nil, "employee_message[receiver_id]", @message_list, :username, :name %><br>
            <%= label_tag :title %><br>
            <%= text_field_tag "employee_message[title]" %><br>
            <%= text_area_tag "employee_message[content]" %><br>
            <%= hidden_field_tag "employee_message[sender_id]", @employee.id %>
            <%= hidden_field_tag "employee_message[sender]", @employee.username %>
            <%= submit_tag "Send" %>
          <% end %>
        </div>
        <h3>Manager: </h3>
        <ul class="list-group">
          <li class="list-group-item"><%= link_to @employee.manager.name, common_show_path(:username => @employee.manager.username) %></li>
        <h3>Coworkers: </h3>
            <% @coworkers.each do |coworker| %>
              <li class="list-group-item"><%= link_to coworker.name, common_show_path(:username => coworker.username) %><span class="badge"><%= coworker.tasks.count %></span></li>
            <% end %>
          </ul>
      </ul><br>
    </div>
    </div>
    <br>
    <div class="col-sm-9">
      <div class="well">
        <h4>Task</h4>
        <% @employeetasks.each do |employeetask| %>
          <div class="panel-group">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h4 class="panel-title">
                  <a data-toggle="collapse" href=<%= "#" + "#{employeetask.id}" %> ><%= employeetask.task.name %></a>
                </h4>
              </div>
              <div id=<%= employeetask.id %> class="panel-collapse collapse">
                <div class="panel-body">
                  <p>Project:
                  <%= link_to employeetask.task.project.name, employeetask.task.project %>
                  </p>
                  Total Working Time: <%= employeetask.task.total_working_time %>
                  <br>
                </div>

                <div class="progress">
                  <div class="progress-bar" role="progressbar" aria-valuenow="70"
                  aria-valuemin="0" aria-valuemax="100" style=<%= "width:" + "#{@utility.task_progress(employeetask.task)}" + "%" %> >
                    <%= "#{@utility.task_progress(employeetask.task)}" + "%" %>
                  </div>
                </div>

                <div class="panel-footer"><%= link_to "Report Progress", edit_employee_task_path(employeetask) %></div>

              </div>
            </div>
          </div>
        <% end %>





        </div>
      </div>