config/routes.rb
Rails.application.routes.draw do
  resources :employee_messages
  resources :mails
  resources :employee_tasks
  resources :tasks
  resources :projects
  resources :managers
  resources :employees
  resources :login, only: [:new, :create]

  root 'application#hello'
  post "/message_redirect", to: "common_pages#message_redirect", as: "message_redirect"
  get "/logout", to: "login#destroy", as: "logout"
  get "/show/:username", to: "common_pages#show", as: "common_show"
  get "/managers/:id/edit_employees", to: "managers#edit_employees", as: "edit_employees"
  post "/employees/got_fired", to: "employees#got_fired", as: "got_fired"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/manager.rb
class Manager < ApplicationRecord
  has_many :projects
  has_many :employees
  has_many :mails

  has_secure_password

  validates :username, uniqueness: true

end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  before_action :find_manager, only: [:show, :edit, :update, :edit_employees, :destroy]
  skip_before_action :authorized?, only: [:new, :create]

  def show
    if @manager.username == session[:user_username]
      @message_list = @manager.employees
      @manager_messages = @manager.mails.select {|mail| mail.sender != @manager.username}.sort_by {|mail| mail.id}.reverse
      @sent_messages = @manager.mails.select {|mail| mail.sender == @manager.username}.sort_by {|mail| mail.id}.reverse

      if @manager_messages.length < 3
        @recent_three_messages = @manager_messages
      else
        @recent_three_messages = @manager_messages[0..2]
      end
    else
      redirect_to common_show_path(:username => @manager.username)
    end
  end

  def new
    @manager = Manager.new
  end

  def create
    # byebug
    params[:manager][:username] = "mag" << params[:manager][:username]
    manager = Manager.create(manager_params(:name, :username, :password))
    redirect_to new_login_path
  end

  def edit_employees
    if @manager.username == session[:user_username]
      @employees = @manager.employees
    else
      redirect_to @user
    end

  end

  def update
    if @manager.username == session[:user_username]
      return redirect_to @user
    end
    password = params[:manager][:password]
    password2 = params[:manager][:confirm_password]
    if @utility.double_chack_passowrd(password, password2)
      @manager.update(manager_params(:name, :password))
      redirect_to @manager
    else
      flash[:messages] = "Password is not match"
      redirect_to @edit_account_path
    end
  end
end


def find_manager
  @manager = Manager.find(params[:id])
  @quote = Faker::TvShows::GameOfThrones.quote
end

def manager_params(*argu)
  params.require(:manager).permit(*argu)
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/views/managers/edit.html.erb
<div class="jumbotron">
  <div class="container text-center">
    <h1>Account Setting</h1>
    <h2><%= @manager.name %></h2>
    <p><%= @quote %></p>
  </div>
</div>

<div class="emp_container container-fluid text-center">
  <div class="row content">
    <div class="col-sm-4 sidenav">
    </div>
    <div class="emp_form col-sm-4 text-left">
    <div class="form_cont">
      <h2>Edit Account</h2>
      <% if flash[:messages] %>
        <p><%= flash[:messages] %></p>
      <% end %>
      <%= form_for @manager do |f|%>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, :class => "form-control", placeholder: 'Name' %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, :class => "form-control", placeholder: 'Password' %>
        </div>
        <div class="form-group">
          <%= f.label "Confirm Password" %>
          <%= f.password_field :confirm_password, :class => "form-control", placeholder: 'Confirm Password' %>
        </div>
        <%= submit_tag "Update", :class => "btn btn-primary"%>
      <% end %>
      <button class="btn btn-danger" data-toggle="collapse" data-target="#demo">Delete Account</button>
      <div id="demo" class="collapse">
        <%= form_tag manager_path(@manager), method: :"delete" do %>
          <%= submit_tag "confirm", :class => "btn btn-danger" %>
        <% end %>
      </div>
      </div>
    </div>
    <div class="col-sm-4 sidenav">
    </div>
  </div>
</div>

app/views/managers/edit_employees.html.erb
<div class="jumbotron well">
  <div class="container">
    <h1 class="display-3"><%= @user.name %></h1>
    <h3>Manager</h3>
    <p>Power is a curious thing. Who lives, Who dies. Power resides where men believe it resides. It is a trick, A shadow on the wall.</p>
  </div>
</div>

<div class="container-fluid">
  <div class="row content">
    <br>
    <div class="col-sm-12">
      <div class="well">
        <div class="panel-group">
          <div class="panel panel-default">
            <% @employees.each do |employee| %>
            <div class="panel-heading">
              <h4 class="panel-title">
                <a data-toggle="collapse" href=<%= "#" + "#{employee.id}"  %>><%= employee.name %></a>
              </h4>
            </div>
            <div id=<%= "#{employee.id}" %> class="panel-collapse collapse">
              <div class="panel-body">Task:
                <% employee.tasks.each do |task| %>
                  <%= task.name %>
                <% end %>
              </div>
              <div class="panel-footer"><button class="btn btn-danger btn-xs" data-toggle="collapse" data-target=<%= "#delete" + "#{employee.id}"  %>> Fire!!! </button>
                <div id=<%= "delete#{employee.id}" %> class="collapse">
                  <%= form_tag "/employees/got_fired", method: :"post" do %>
                    <%= hidden_field_tag "employee_id", employee.id %>
                    <%= submit_tag "confirm", :class => "btn btn-danger btn-xs" %>
                  <% end %>
                </div>
              </div>
            </div>
            <% end %>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/managers/junk.html.erb
<footer class="footer">
    <div class="container">
    <span class="text-muted">Mod2 2019</span>
    </div>
</footer>




<div class="container">
        <form class="form-signin">
        <img class="mb-4" src="/docs/4.3/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
        <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
        <div class="checkbox mb-3">
            <label>
            <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        <p class="mt-5 mb-3 text-muted">&copy; 2017-2019</p>
        </form>
</div>





<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav hidden-xs">
      <h2>Employees</h2>
      <ul class="list-group">
                <% @manager.employees.each do |employee| %>
                    <li class="list-group-item"><%= link_to employee.name, employee %></li>  
                <% end %>
            </ul> 
    </div>
    <br>



    
    <div class="container">
      <h2>Projects</h2>
            <ul class="list-group">
                <% @manager.projects.each do |project| %>
                    <li class="list-group-item"><%= link_to project.name, project %> -- <%= project.description %></li>  
                <% end %>
            </ul> 
    </div>




        <div class="col">
          <div class="well">
            <h4>Sessions</h4>
            <p>10 Million</p> 
          </div>
        </div>
        <div class="col">
          <div class="well">
            <h4>Bounce</h4>
            <p>30%</p> 
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-4">
          <div class="well">
            <p>Text</p> 
            <p>Text</p> 
            <p>Text</p> 
          </div>
        </div>
        <div class="col-sm-4">
          <div class="well">
            <p>Text</p> 
            <p>Text</p> 
            <p>Text</p> 
          </div>
        </div>
        <div class="col-sm-4">
          <div class="well">
            <p>Text</p> 
            <p>Text</p> 
            <p>Text</p> 
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-8">
          <div class="well">
            <p>Text</p> 
          </div>
        </div>



        <%= for_for @manager, html: {class: "Test"} do |f| %>



       <%= button_to "Visit Project", @manager.projects.second, method: 'get', :class => "btn btn-primary" %> <br>




<h4>Projects</h4>
              <% @manager.projects.each do |project| %>
                <div class="accordion" id="accordionExample">
                    <div class="card">
                      <div class="card-header" id="headingOne">
                        <h2 class="mb-0">
                          <button class="btn btn-link" type="button" data-toggle="collapse" data-target=<%= "#" + "#{project.id}" %> aria-expanded="false" aria-controls="collapseOne">
                            <%= project.name %>
                          </button>
                        </h2>
                      </div>
                    <div id=<%= project.id %> class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
                  <div class="card-body">
              <%= project.description %>
          </div>
      </div>
    </div> 
  </div>
            <% end %>
        

app/views/managers/new.html.erb
<div class="emp_container container-fluid text-center">
  <div class="row content">
    <div class="col-sm-4 sidenav">
    </div>
    <div class="emp_form col-sm-4 text-left">
    <div class="form_cont">
      <h1>Welcome</h1>
      <h2>Managers Login</h2>
      <% if flash[:messages] %>
        <p><%= flash[:messages] %></p>
      <% end %>
      <%= form_for @manager do |f|%>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, :class => "form-control", placeholder: 'Name' %>
        </div>
        <div class="form-group">
          <%= f.label :username %>
          <%= f.text_field :username, :class => "form-control", placeholder: 'Username' %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, :class => "form-control", placeholder: 'Password' %>
        </div>
        <%= submit_tag "Submit", :class => "btn btn-primary"%>
      <% end %>
      </div>
    </div>
    <div class="col-sm-4 sidenav">
    </div>
  </div>
</div>

app/views/managers/show.html.erb
<div class="jumbotron well">
  <div class="container">
    <h1 class="display-3"><%= @manager.name %></h1>
    <h3>Manager</h3>
    <p><%= @quote %></p>
  </div >
</div >


<div class="container-fluid">
  <div class="row content">
      <div class="col-sm-3 emp-inbox">
        <div class="well" style="margin-top: 20px;">
        <ul class=" nav nav-pills nav-stacked create-project">
          <li id="li" class="active"><a href="/projects/new">Create Project</a></li>
        </ul>
        <ul class="mag-nav nav nav-pills nav-stacked">
        <li class="active inbox"><a data-toggle="collapse" href="#inbox">Inbox<span class="badge"><%= @manager_messages.count %></span></a></li>
        <div id="inbox" class="panel-collapse collapse">
          <ul>
            Employee Messages
            <% if @manager_messages == [] %>
              <p>No Message</p>
            <% else %>
              <% @manager_messages.each do |message| %>
                <li><a data-toggle="collapse" href=<%= "#emp_mesg" + "#{message.id}" %>><%= message.title %> form <%= @utility.sender_name(message) %></a></li>
                <div id=<%= "emp_mesg#{message.id}" %> class="panel-collapse collapse">
                  <%= message.content %>
                </div>
              <% end %>
            <% end %>
          </ul>
          <br>
          <ul>
            Sent Messages
            <% if @sent_messages == [] %>
              <p>No Message</p>
            <% else %>
              <% @sent_messages.each do |message| %>
                <li><a data-toggle="collapse" href=<%= "#set_mesg" + "#{message.id}" %>><%= message.title %> to <%= message.employee.name %></a></li>
                <div id=<%= "set_mesg#{message.id}" %> class="panel-collapse collapse">
                  <%= message.content %>
                </div>
              <% end %>
            <% end %>
          </ul>
          <br>
        </div>
        <li class="active"><a data-toggle="collapse" href="#message">Send Message</a></li>
        <div id="message" class="panel-collapse collapse">
          <%= form_tag "/mails", method: :"post" do%>
            <%= label_tag "Send to" %>
            <%= collection_select nil, "manager_message[employee_id]", @message_list, :id, :name %><br>
            <%= label_tag :title %><br>
            <%= text_field_tag "manager_message[title]" %><br>
            <%= text_area_tag "manager_message[content]" %><br>
            <%= hidden_field_tag "manager_message[manager_id]", @manager.id %>
            <%= hidden_field_tag "manager_message[sender]", @manager.username %>
            <%= submit_tag "Send" %>
          <% end %>
        </div>



        <h2>Employees</h2>
        <ul class="list-group">
            <% @manager.employees.each do |employee| %>
              <li class="list-group-item"><%= link_to employee.name, employee %><span class="badge"><%= employee.tasks.count %></span></li>
            <% end %>
        </ul>
        </ul>
        </div>
      </div>
      <br>

      <div class="col-sm-9">
          <div class="well">
            <h4>New Messages</h4>
              <ul class="list-group">
                <% @recent_three_messages.each do |message| %>
                  <li class="list-group-item"><%= "#{message.title} from #{message.employee.name}" %> -- <%= message.content.length > 100? message.content[0..100]+ "..." : message.content %></li>
                <% end %>
              </ul>
          </div>
          <div class="well">
            <h4>Projects</h4>
              <% @manager.projects.each do |project| %>
               <div class="panel-group">
                  <div class="panel panel-default">
                    <div class="panel-heading">
                      <h4 class="panel-title">
                        <a data-toggle="collapse" href=<%= "#" + "#{project.id}" %>><%= project.name %></a>
                      </h4>
                    </div>
                    <div id=<%= project.id %> class="panel-collapse collapse">
                      <div class="panel-body"><%= project.description %></div>

                      <div class="progress">
                        <div class="progress-bar" role="progressbar" aria-valuenow="70"
                        aria-valuemin="0" aria-valuemax="100" style=<%= "width:" + "#{@utility.project_progress(project)}" + "%" %> >
                          <%= "#{@utility.project_progress(project)}" + "%" %>
                        </div>
                      </div>

                      <div class="panel-footer"><%= link_to "View Project", project %></div>
                    </div>
                  </div>
                </div>
              <% end %>
          </div>
      </div>
    </div>
  </div>