config/routes.rb
Rails.application.routes.draw do
  resources :employee_messages
  resources :mails
  resources :employee_tasks
  resources :tasks
  resources :projects
  resources :managers
  resources :employees
  resources :login, only: [:new, :create]

  root 'application#hello'
  post "/message_redirect", to: "common_pages#message_redirect", as: "message_redirect"
  get "/logout", to: "login#destroy", as: "logout"
  get "/show/:username", to: "common_pages#show", as: "common_show"
  get "/managers/:id/edit_employees", to: "managers#edit_employees", as: "edit_employees"
  post "/employees/got_fired", to: "employees#got_fired", as: "got_fired"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :manager
  has_many :tasks, :dependent => :destroy

  validates :name, presence: true

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :edit, :update, :destroy]

  def show
    @edit_check = false
    if @project.manager.username == session[:user_username]
      @edit_check = true
    end
    session[:project_id] = @project.id
    @employees = @project.manager.employees
    @tasks = @project.tasks
  end

  def new
    username = session[:user_username]
    if @manager_check
      @manager = Manager.find_by(username: username)
      @project = Project.new
    else
      redirect_to employee_path(Employee.find_by(username: session[:user_username]))
    end
  end

  def create
    project = Project.create(project_params(:name, :description, :manager_id))
    redirect_to project
  end

  def edit

  end

  def update
    @project.update(project_params(:name, :description))
    redirect_to @project
  end

  def destroy
    @project.destroy
    redirect_to @user
  end
end

def project_params(*argu)
  params.require(:project).permit(*argu)
end

def find_project
  @project = Project.find(params[:id])
  @quote = Faker::Movies::StarWars.quote
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<div class="jumbotron">
  <div class="container text-center">
    <h1>Account Setting</h1>
    <h2><%= @project.name %></h2>
    <p><%= @quote %></p>
  </div>
</div>

<div class="emp_container container-fluid text-center">
  <div class="row content">
    <div class="col-sm-4 sidenav">
    </div>
    <div class="emp_form col-sm-4 text-left">
    <div class="form_cont">
      <h2>Edit Account</h2>
      <% if flash[:messages] %>
        <p><%= flash[:messages] %></p>
      <% end %>
      <%= form_for @project do |f|%>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, :class => "form-control", placeholder: 'Name' %>
        </div>
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, :class => "form-control"%>
        </div>
        <%= submit_tag "Update", :class => "btn btn-primary"%>
      <% end %>
      <button class="btn btn-danger" data-toggle="collapse" data-target="#demo">Delete Account</button>
      <div id="demo" class="collapse">
        <%= form_tag project_path(@project), method: :"delete" do %>
          <%= submit_tag "confirm", :class => "btn btn-danger" %>
        <% end %>
      </div>
      </div>
    </div>
    <div class="col-sm-4 sidenav">
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="emp_container container-fluid text-center">
  <div class="row content">
    <div class="col-sm-4 sidenav">
    </div>
    <div class="col-sm-4 text-left">
      <h1 class="display-3">Creat Project</h1>
    <p><%= @quote %></p>
      <% if flash[:messages] %>
        <p><%= flash[:messages] %></p>
      <% end %>
      <%= form_for @project do |f|%>
        <div class="form-group">
          <%= f.label :name, "Project Title" %>
          <%= f.text_field :name, :class => "form-control", placeholder: 'Project Title' %>
        </div>
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, :class => "form-control"%>
        </div>
          <%= f.hidden_field :manager_id, :value => @manager.id %>
        <%= submit_tag "Submit", :class => "btn-create-project btn btn-primary"%>
      <% end %>
    </div>
    <div class="col-sm-4 sidenav">
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="jumbotron well">
  <div class="container">
    <h1 class="display-3"><%= @project.name %></h1>
    <h3 class="display-3"><%= @project.manager.name %></h3>
    <p><%= @quote %></p>
  </div >
</div >


<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav hidden-xs well">
      <% if @edit_check == true %>
        <ul class="nav nav-pills nav-stacked create-project">
          <li id="li" class="active"><a data-toggle="collapse" href="#demo">Create Task</a></li>
        </ul>
        <div id="demo" class="collapse">
          <%= label_tag "# of Task (maxmiun 5)" %>
          <%= form_tag "/tasks/new", method: :"get" do%>
            <%= number_field_tag :amount %>
            <%= submit_tag "Create" %>
          <% end %>
          <br>
        </div>
        <ul class="nav nav-pills nav-stacked">
          <li class="active"><%= link_to "Edit Project", edit_project_path(@project) %></li>
        </ul>
        <% end %>
      <ul class="nav nav-pills nav-stacked">
        <h3>Employees</h3>
        <ul class="list-group">
        <% @employees.each do |employee| %>
          <li class="list-group-item"><%= link_to employee.name, common_show_path(:username => employee.username) %><span class="badge"><%= employee.tasks.count %></span></li>
        <% end %>
      </ul><br>
    </div>
    <br>

    <div class="col-sm-9">
      <div class="well">
        <h4>Project Progress</h4>
          <ul class="list-group">
            <li class="list-group-item">Total Working Done: <%= @utility.project_work_done(@project) %></li>
            <li class="list-group-item">Total Working Load: <%= @utility.project_work_loade(@project) %></li>
            <div class="progress">
              <div class="progress-bar" role="progressbar" aria-valuenow="70"
              aria-valuemin="0" aria-valuemax="100" style=<%= "width:" + "#{@utility.project_progress(@project)}" + "%" %> >
                <%= "#{@utility.project_progress(@project)}" + "%" %>
              </div>
            </div>
          </ul>
      </div>
      <div class="well">
        <h4>Tasks</h4>
        <% @tasks.each do |task| %>
        <div class="panel-group">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4 class="panel-title">
                <a data-toggle="collapse" href=<%= "#" + "#{task.id}" %>> <%= task.name %> </a>
              </h4>
            </div>
            <div id=<%= task.id %> class="panel-collapse collapse">
              <div class="panel-body"><%= @utility.task_employees(task) %></div>
              <div class="panel-body">Total Woring Done: <%= task.total_working_done %></div>
              <div class="panel-body">Total working Load: <%= task.total_working_time %></div>
              <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="70"
                aria-valuemin="0" aria-valuemax="100" style=<%= "width:" + "#{@utility.task_progress(task)}" + "%" %> >
                  <%= "#{@utility.task_progress(task)}" + "%" %>
                </div>
              </div>
              <% if @edit_check == true %>
              <div class="panel-footer"><%= link_to "Edit", edit_task_path(task) %>
                <%= form_tag task, method: :delete do %>
                  <%= submit_tag "Delete" %>
                <% end %>
              </div>
              <% end %>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>